services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://simaosousa16:kZiFb8yDGj2sM8V9@francesinhaswikidb.is06k0l.mongodb.net/?retryWrites=true&w=majority&appName=FrancesinhasWikiDB

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:


